worker_processes  auto;
worker_rlimit_nofile 500000;

error_log  /home/venom/logs/nginx/default_error.log warn;
pid        /home/venom/data/runtime/pid/nginx.pid;

events {
    worker_connections  32000;
    use epoll;
    accept_mutex on;
    multi_accept on;
}

# Optimized thread pool
thread_pool venom_pool threads=64 max_queue=0;

http {
    # WebSocket upgrade mapping for code-server
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    # Load global configurations
    include global.conf;
    include balance.conf;
    include ssl.conf;
    include security.conf;

    # Load all sites
    include /home/venom/nginx/sites/*.conf;
}
