[XkQ9zP]
user = venom
group = venom

listen = /home/venom/data/runtime/sockets/XkQ9zP.sock
listen.owner = venom
listen.group = venom
listen.mode = 0660
listen.backlog = 512
pm = dynamic
pm.max_children = 20
pm.start_servers = 5
pm.min_spare_servers = 3
pm.max_spare_servers = 10
pm.max_requests = 1000

request_terminate_timeout = 60s

security.limit_extensions = .php

php_admin_value[error_log] = /home/venom/logs/php-fpm/XkQ9zP.log
php_admin_value[memory_limit] = 128M
php_admin_value[max_execution_time] = 30

env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TEMP] = /home/venom/data/cache
clear_env = yes
php_admin_value[disable_functions] = exec,shell_exec,system,passthru,proc_open,popen,pcntl_exec,pcntl_fork,pcntl_signal,pcntl_alarm
php_admin_value[open_basedir] = /home/venom/wwwdir:/home/venom/workspace:/home/venom/whmcs:/tmp:/home/venom/data/runtime/sessions:/home/venom/data/cache:/usr/local
