[global]
pid = /home/venom/data/runtime/pid/php-fpm.pid
error_log = /home/venom/logs/php-fpm/php-fpm.log
log_level = warning
emergency_restart_threshold = 100
emergency_restart_interval = 60s
process_control_timeout = 30s
daemonize = yes
rlimit_files = 1048576
rlimit_core = unlimited
events.mechanism = epoll
process.max = 1024

include=/home/venom/php/etc/pools.d/*.conf
